/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.scene.text.Text;
import javafx.stage.Stage;

public class App extends Application {
    private Stage stage;

    @Override
    public void start(Stage mainStage) {
        //handling stage
        stage = mainStage;
        
        //stage
        stage.setTitle("Tugas Projek OOP");
        stage.setScene(getScene1());
        stage.show();
    }

    private Scene getScene1(){

        Text tTitle = new Text("Aplikasi Perhitungan Kalori");
        Button bMulai = new Button("Mulai");
        VBox sectionRight = new VBox(tTitle, bMulai);
        sectionRight.setSpacing(50);
        sectionRight.setAlignment(Pos.CENTER);
        sectionRight.setPrefWidth(30);

        //Action untuk Button
        bMulai.setOnAction(v->{
            stage.setScene(getScene2());
        });

        //section
        //ImageView ivBanner = new ImageView();
        //ivBanner.setFitWidth(260);
        //ivBanner.setFitHeight(300);
        //ivBanner.setPreserveRatio(True);

        //rootNode
        VBox rootNode = new VBox(sectionRight);
        rootNode.setAlignment(Pos.CENTER);

        Scene scene = new Scene(new StackPane(rootNode),640, 480);

        //atur css
        //scene.getStylesheets().add(getClass().getResource("/styles/style.css").toExternalForm());
        return scene;
    }

    private Scene getScene2(){
        Text tTitle = new Text("PILIH MENU OLAHRAGA");
        Button bOlahraga1 = new Button("RUNNING");
        Button bOlahraga2 = new Button("CYCLING");
        Button bOlahraga3 = new Button("SWIMMING");
        VBox sectionRight = new VBox(tTitle, bOlahraga1, bOlahraga2, bOlahraga3);
        sectionRight.setSpacing(50);
        sectionRight.setAlignment(Pos.CENTER);
        sectionRight.setPrefWidth(30);

        //Action untuk Button
        //.setOnAction(v->{
          //  stage.setScene(getScene2());
        ///});

        //section
        //ImageView ivBanner = new ImageView();
        //ivBanner.setFitWidth(260);
        //ivBanner.setFitHeight(300);
        //ivBanner.setPreserveRatio(True);

        //rootNode
        VBox rootNode = new VBox(sectionRight);
        rootNode.setAlignment(Pos.CENTER);

        Scene scene = new Scene(new StackPane(rootNode),640, 480);

        //atur css
        //scene.getStylesheets().add(getClass().getResource("/styles/style.css").toExternalForm());
        return scene;
    }
    


    public static void main(String[] args) {
        launch(args);
    }

}
